Vagrant.configure("2") do |config|
  
  #config.hostmanager.enabled = true 
  #config.hostmanager.manage_host = true
  #config.vm.boot_timeout = 900

  config.vm.define "mongodb" do |server|
    server.vm.box = "geerlingguy/ubuntu2004"
    server.vm.hostname = "mongodb"
    server.vm.network "public_network", ip: "192.168.0.10"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.name = "mongodb"
      vb.cpus = "2"
	end
  #server.vm.provision "shell", path: "data/*.sh"
	end
end
