version: '3'
services:
  redis:
    image: redislabs/redismod
    container_name: otus-redis
    ports:
      - 6379:6379
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - '8001:8001'
    volumes:
      - ./redisinsight:/db