Vagrant.configure("2") do |config|
  
  #config.hostmanager.enabled = true 
  #config.hostmanager.manage_host = true
  #config.vm.boot_timeout = 900

  # ReplicaSet Mongo Primary + Secondary + Arbiter 
  config.vm.define "mongo-map-reduce" do |server|
    server.vm.box = "geerlingguy/ubuntu2004"
    server.vm.hostname = "mongo-map-reduce"
    server.vm.network "public_network", ip: "192.168.0.77"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.name = "mongo-map-reduce"
      vb.cpus = "4"
  	end
  server.vm.provision "shell", path: "./provision.sh"
  end
end
