Vagrant.configure("2") do |config|

  config.vm.define "otus-tarantool" do |server|
    server.vbguest.auto_update = false if Vagrant.has_plugin?('vagrant-vbguest')
    server.vm.box = "geerlingguy/ubuntu2004"
    server.vm.hostname = "otus-tarantool"
    server.vm.network "public_network", ip: "192.168.0.190", bridge: "wlo1"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "8192"
      vb.name = "otus-tarantool"
      vb.cpus = "8"
    end
    server.vm.provision "shell", inline: <<-SHELL
    curl -L https://tarantool.io/YxTjzWB/release/2/installer.sh | bash
    sudo apt-get -y install tarantool
    SHELL
  end
end