Vagrant.configure("2") do |config|
  
  (1..4).each do |i|
    config.vm.define "etcd-#{i}" do |server|
      server.vm.box = "geerlingguy/ubuntu2004"
      server.vm.hostname = "etcd-#{i}"
      server.vm.network "public_network", ip: "192.168.0.7#{i}"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.name = "etcd-#{i}"
        vb.cpus = "2"
      end
    server.vm.provision "shell", path: "./provision.sh"
    end
  end
end
