Vagrant.configure("2") do |config|
  
  config.vm.define "zookeeper1" do |server|
    server.vm.box = "geerlingguy/ubuntu2004"
    server.vm.hostname = "zookeeper1"
    server.vm.network "public_network", ip: "192.168.0.140"
    server.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.name = "zookeeper1"
      vb.cpus = "2"
  	end
  #server.vm.provision "shell", path: "./provision.sh"
  end

  (1..3).each do |i|
    config.vm.define "click#{i}" do |server|
      server.vm.box = "geerlingguy/ubuntu2004"
      server.vm.hostname = "click#{i}"
      server.vm.network "public_network", ip: "192.168.0.14#{i}"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "3072"
        vb.name = "click#{i}"
        vb.cpus = "4"
      end
    server.vm.provision "shell", path: "./provision.sh"
    end
  end
end
