version: '3'

networks:
  neo4j_network:

services:
  leader:
    image: neo4j:5.6-enterprise
    networks:
      - neo4j_network
    ports:
      - '7474:7474'
      - '7687:7687'
      - '2004:2004'
    volumes:
      - ./neo4j_data/leader/data:/data
      - ./neo4j_data/leader/logs:/logs
      - ./neo4j_data/leader/metrics:/metrics
    environment:
      - NEO4J_AUTH=neo4j/neo4jtest
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server.cluster.system_database_mode=PRIMARY
      - NEO4J_initial.server.mode_constraint=PRIMARY
      - NEO4J_causal.clustering.expected_core_cluster_size=4
      - NEO4J_causal.clustering.initial_discovery_members=leader:5000,follower1:5000,follower2:5000,replica:5000
      - NEO4J_causal.clustering.discovery_advertised_address=leader:5000
      - NEO4J_server.metrics.enabled=true
      - NEO4J_server.metrics.prometheus.enabled=true
      - NEO4J_server.metrics.prometheus.endpoint=0.0.0.0:2004

  follower1:
    image: neo4j:5.6-enterprise
    networks:
      - neo4j_network
    ports:
      - '7475:7474'
      - '7688:7687'
    volumes:
      - ./neo4j_data/follower1/data:/data
      - ./neo4j_data/follower1/logs:/logs
      - ./neo4j_data/leader/metrics:/metrics
    environment:
      - NEO4J_AUTH=neo4j/neo4jtest
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server.cluster.system_database_mode=FOLLOWER
      - NEO4J_initial.server.mode_constraint=FOLLOWER
      - NEO4J_causal.clustering.expected_core_cluster_size=4
      - NEO4J_causal.clustering.initial_discovery_members=leader:5000,follower1:5000,follower2:5000,replica:5000
      - NEO4J_causal.clustering.discovery_advertised_address=follower1:5000

  follower2:
    image: neo4j:5.6-enterprise
    networks:
      - neo4j_network
    ports:
      - '7476:7474'
      - '7689:7687'
    volumes:
      - ./neo4j_data/follower2/data:/data
      - ./neo4j_data/follower2/logs:/logs
      - ./neo4j_data/leader/metrics:/metrics
    environment:
      - NEO4J_AUTH=neo4j/neo4jtest
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server.cluster.system_database_mode=FOLLOWER
      - NEO4J_initial.server.mode_constraint=FOLLOWER
      - NEO4J_causal.clustering.expected_core_cluster_size=4
      - NEO4J_causal.clustering.initial_discovery_members=leader:5000,follower1:5000,follower2:5000,replica:5000
      - NEO4J_causal.clustering.discovery_advertised_address=follower2:5000

  replica:
    image: neo4j:5.6-enterprise
    networks:
      - neo4j_network
    ports:
      - '7477:7474'
      - '7690:7687'
    volumes:
      - ./neo4j_data/replica/data:/data
      - ./neo4j_data/replica/logs:/logs
      - ./neo4j_data/leader/metrics:/metrics
    environment:
      - NEO4J_AUTH=neo4j/neo4jtest
      - NEO4J_server_default__listen__address=0.0.0.0
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server.cluster.system_database_mode=READ_REPLICA
      - NEO4J_initial.server.mode_constraint=READ_REPLICA
      - NEO4J_causal.clustering.expected_core_cluster_size=4
      - NEO4J_causal.clustering.initial_discovery_members=leader:5000,follower1:5000,follower2:5000,replica:5000
      - NEO4J_causal.clustering.discovery_advertised_address=replica:5000
