Vagrant.configure("2") do |config|

  (1..4).each do |i|
    config.vm.define "cb#{i}" do |server|
      server.vm.box = "geerlingguy/ubuntu2004"
      server.vm.hostname = "cb#{i}"
      server.vm.network "public_network", ip: "192.168.0.13#{i}"
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "3072"
        vb.name = "cb#{i}"
        vb.cpus = "3"
      end
    server.vm.provision "shell", path: "./provision.sh"
    end
  end
end
