- name: Test blocks
  hosts: all
  become: yes

  vars:



  tasks:

  - block:

    - name: Install Pakages
      apt:
        pkg:
          - tree
          - nmon
          - htop
        state: present
  
    - name: Create Folder
      file:
        path: /srv/folder1
        state: directory

    when: ansible_hostname == "edit"

  - name: Copy file
    copy:
      src: ../data/testfile
      dest: /srv/
      mode: 0777
    when: ansible_hostname == "job"