- name: Loops
  hosts: all
  become: yes

  tasks:
    - name: Create folder
      file:
        path: "/home/{{item}}"
        state: directory
      loop:
        - dir1
        - dir2
        - dir3