---
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka1:
    image: confluentinc/cp-kafka:7.0.9
    hostname: kafka1
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: HOST_LISTENER://0.0.0.0:9092, INT_LISTENER://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST_LISTENER:PLAINTEXT, INT_LISTENER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: HOST_LISTENER://localhost:9092, INT_LISTENER://kafka1:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INT_LISTENER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  kafka2:
    image: confluentinc/cp-kafka:7.0.9
    hostname: kafka2
    ports:
      - '9093:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: HOST_LISTENER://0.0.0.0:9092, INT_LISTENER://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST_LISTENER:PLAINTEXT, INT_LISTENER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: HOST_LISTENER://localhost:9093, INT_LISTENER://kafka2:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INT_LISTENER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  kafka3:
    image: confluentinc/cp-kafka:7.0.9
    hostname: kafka3
    ports:
      - '9094:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: HOST_LISTENER://0.0.0.0:9092, INT_LISTENER://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: HOST_LISTENER:PLAINTEXT, INT_LISTENER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: HOST_LISTENER://localhost:9094, INT_LISTENER://kafka3:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: INT_LISTENER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka1:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - zookeeper
      - kafka1
      - kafka2
      - kafka3