---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-data-cassandra-0
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: "cassandra-group-snapshot-cassandra-data-cassandra-0-9e01f2bd-230b-4666-bd49-7e63662138a2"
spec:
  accessModes:
     - ReadWriteOnce
  storageClassName: stork-snapshot-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-data-cassandra-1
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: "cassandra-group-snapshot-cassandra-data-cassandra-1-9e01f2bd-230b-4666-bd49-7e63662138a2"
spec:
  accessModes:
     - ReadWriteOnce
  storageClassName: stork-snapshot-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-data-cassandra-2
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: "cassandra-group-snapshot-cassandra-data-cassandra-2-9e01f2bd-230b-4666-bd49-7e63662138a2"
spec:
  accessModes:
     - ReadWriteOnce
  storageClassName: stork-snapshot-sc
  resources:
    requests:
      storage: 10Gi
---